'use client';
import {useState} from 'react';
import {ChevronDown,Sparkles,Trash2,Check,PenLine} from 'lucide-react';
import {ReadingEntry,Question} from '../lib/types';
import {repository} from '../lib/storage';
export function EntryCard({entry,questions,onEdit,onAnswer,onDeleteQuestion,onDelete,onAI,busy}:{entry:ReadingEntry;questions:Question[];onEdit:(e:ReadingEntry)=>boolean;onAnswer:(q:Question)=>boolean;onDeleteQuestion:(id:string)=>void;onDelete:()=>void;onAI:(mode:'organize'|'questions')=>void;busy:boolean}){
 const [editing,setEditing]=useState(false);const [values,setValues]=useState({summary:entry.summary,thoughts:entry.thoughts,lessons:entry.lessons});
 return <details className="entry" open><summary><div><span className="entry-date">{entry.date.replaceAll('-','. ')}</span><span className="page-tag">{entry.startPage}—{entry.endPage}p</span>{entry.aiStatus==='sample'&&<span className="sample">예시 기록</span>}</div><ChevronDown size={18}/></summary><div className="entry-body"><div className="entry-tools"><span className="small muted">{questions.filter(q=>q.answeredAt).length}개의 생각을 남겼어요</span><div><button className="text-button" disabled={busy} onClick={()=>{setValues({summary:entry.summary,thoughts:entry.thoughts,lessons:entry.lessons});setEditing(!editing)}}><PenLine size={14}/>직접 정리</button><button className="icon muted" aria-label="독서 기록 삭제" disabled={busy} onClick={onDelete}><Trash2 size={16}/></button></div></div>{editing?<form onSubmit={e=>{e.preventDefault();if(onEdit({...entry,...values}))setEditing(false)}}>{(['summary','thoughts','lessons'] as const).map((k,i)=><label key={k}>{['내용 요약','나의 생각','얻은 교훈'][i]}<textarea value={values[k]} onChange={e=>setValues({...values,[k]:e.target.value})}/></label>)}<button className="primary" type="submit">정리 저장</button></form>:<>{entry.summary||entry.thoughts||entry.lessons?(['summary','thoughts','lessons'] as const).map((k,i)=><section className="prose" key={k}><h3>{['내용 요약','나의 생각','얻은 교훈'][i]}</h3><p>{entry[k]||'아직 적힌 내용이 없어요.'}</p></section>):<section className="prose"><h3>내 기록</h3><p>{entry.originalText}</p></section>}</>}
 <details className="original"><summary>내 원문 보기</summary><p>{entry.originalText}</p></details><div className="ai-line"><button className="text-button accent" disabled={busy||editing} onClick={()=>onAI('organize')}><Sparkles size={16}/>{busy?'생각을 정리하고 있어요…':entry.aiStatus==='done'?'AI로 다시 정리':'AI로 기록 정리'}</button><span className="small muted">원문은 그대로 보존돼요</span></div>{entry.aiError&&<p className="ai-notice" role="status">{entry.aiError}</p>}<section className="questions"><div className="section-title"><h3><Sparkles size={17}/> 생각해볼 질문</h3><button className="text-button" disabled={busy} onClick={()=>onAI('questions')}>새 질문 받기</button></div>{questions.length?questions.map((q,i)=><Answer key={q.id} question={q} index={i} onSave={onAnswer} onDelete={()=>onDeleteQuestion(q.id)}/>):<p className="muted">AI가 연결되면 이 기록에서 더 깊이 생각해볼 질문을 받을 수 있어요.</p>}</section></div></details>
}
function Answer({question:q,index,onSave,onDelete}:{question:Question;index:number;onSave:(q:Question)=>boolean;onDelete:()=>void}){const [answer,setAnswer]=useState(()=>{try{return repository.draft<string>('answer:'+q.id)??q.answer}catch{return q.answer}});const [saved,setSaved]=useState(!!q.answeredAt);const [draftError,setDraftError]=useState(false);return <div className="question"><div className="question-title"><span>Q{index+1}.</span><p>{q.question}</p><button className="icon" aria-label={`질문 ${index+1} 삭제`} onClick={onDelete}><Trash2 size={15}/></button></div><textarea aria-label={`질문 ${index+1}에 대한 나의 답변`} value={answer} placeholder="정답은 없어요. 지금의 생각을 남겨보세요." onChange={e=>{setAnswer(e.target.value);setSaved(false);try{repository.saveDraft('answer:'+q.id,e.target.value)}catch{setDraftError(true)}}}/>{draftError&&<p role="alert">임시 저장에 실패했습니다. 답변을 복사해 보관해주세요.</p>}<div className="answer-bottom"><span className="small muted">{saved?<><Check size={14}/> 답변 저장됨</>:'나의 생각'}</span><button disabled={!answer.trim()||saved} onClick={()=>{if(onSave({...q,answer:answer.trim(),answeredAt:new Date().toISOString()})){setSaved(true);repository.clearDraft('answer:'+q.id)}}}>답변 저장</button></div></div>}
