'use client';
import {useEffect,useRef,useState,ReactNode} from 'react';
import {X,Plus,Upload} from 'lucide-react';
import {Book,ReadingEntry,today,uid} from '../lib/types';
import {repository} from '../lib/storage';
export function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close()},[]);return <dialog ref={ref} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}}><div className="modal-head"><h2>{title}</h2><button className="icon" onClick={onClose} aria-label="닫기"><X size={20}/></button></div>{children}</dialog>}
export function BookForm({book,onSave,onClose}:{book?:Book;onSave:(b:Book)=>void;onClose:()=>void}){const [cover,setCover]=useState(book?.cover||'');const [error,setError]=useState('');return <Modal title={book?'책 정보 수정':'새로운 책 추가'} onClose={onClose}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({id:book?.id||uid(),title:String(f.get('title')).trim(),author:String(f.get('author')).trim(),totalPages:f.get('pages')?Number(f.get('pages')):null,currentPage:book?.currentPage||0,cover,createdAt:book?.createdAt||new Date().toISOString()})}}><label>책 제목<input name="title" required maxLength={200} defaultValue={book?.title} placeholder="어떤 책을 읽고 있나요?" autoFocus/></label><label>저자<input name="author" required maxLength={200} defaultValue={book?.author} placeholder="저자 이름"/></label><label>전체 페이지 <span className="muted">선택</span><input name="pages" type="number" min={Math.max(1,book?.currentPage||1)} max={100000} defaultValue={book?.totalPages||''} placeholder="예: 400"/></label><label className="upload"><Upload size={18}/> 표지 이미지 선택 <span className="muted">최대 1MB</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>1024*1024){setError('1MB 이하의 이미지를 선택해주세요.');return}if(!['image/png','image/jpeg','image/webp'].includes(file.type)){setError('PNG, JPG, WebP 이미지를 선택해주세요.');return}const reader=new FileReader();reader.onload=()=>{setCover(String(reader.result));setError('')};reader.readAsDataURL(file)}}/></label>{cover&&<div className="cover-preview"><img src={cover} alt="선택한 표지"/><button type="button" className="text-button" onClick={()=>setCover('')}>표지 제거</button></div>}{error&&<p role="alert">{error}</p>}<div className="form-actions"><button type="button" onClick={onClose}>취소</button><button className="primary" type="submit"><Plus size={17}/>{book?'변경 저장':'책 추가'}</button></div></form></Modal>}
export function EntryForm({book,onSave,onClose}:{book:Book;onSave:(entry:ReadingEntry,ai:boolean)=>boolean;onClose:()=>void}){
 const key='entry:'+book.id;const [draft,setDraft]=useState(()=>{try{return repository.draft<{date:string;startPage:string;endPage:string;originalText:string}>(key)||{date:today(),startPage:String(Math.min(book.currentPage+1,book.totalPages||Infinity)),endPage:'',originalText:''}}catch{return {date:today(),startPage:String(book.currentPage+1),endPage:'',originalText:''}}});const [error,setError]=useState('');const [ai,setAI]=useState(true);const [draftOK,setDraftOK]=useState(true);
 function change(field:string,value:string){const next={...draft,[field]:value};setDraft(next);try{repository.saveDraft(key,next);setDraftOK(true)}catch{setDraftOK(false)}}
 return <Modal title="오늘의 독서 기록" onClose={onClose}><p className="form-sub">{book.title}</p><form onSubmit={e=>{e.preventDefault();const start=Number(draft.startPage),end=Number(draft.endPage);if(end<start){setError('마지막 페이지는 시작 페이지보다 작을 수 없습니다.');return}if(!draft.originalText.trim()){setError('읽고 떠오른 생각을 적어주세요.');return}const saved=onSave({id:uid(),bookId:book.id,date:draft.date,startPage:start,endPage:end,originalText:draft.originalText.trim(),summary:'',thoughts:'',lessons:'',createdAt:new Date().toISOString(),aiStatus:'pending'},ai);if(saved)repository.clearDraft(key)}}><div className="fields"><label>독서 날짜<input type="date" value={draft.date} required onChange={e=>change('date',e.target.value)}/></label><label>시작 페이지<input type="number" min={1} max={book.totalPages||100000} required value={draft.startPage} onChange={e=>change('startPage',e.target.value)}/></label><label>마지막 페이지<input type="number" min={1} max={book.totalPages||100000} required value={draft.endPage} placeholder="어디까지 읽었나요?" onChange={e=>change('endPage',e.target.value)}/></label></div><label>읽고 떠오른 생각<textarea className="writing" value={draft.originalText} maxLength={16000} required autoFocus onChange={e=>change('originalText',e.target.value)} placeholder="기억에 남은 내용, 나의 생각, 일상과 연결되는 순간을 편하게 적어보세요."/></label><div className="draft-note">{draftOK?'작성 중인 내용은 이 브라우저에 임시 보관됩니다.':'임시 저장이 불가능합니다. 닫기 전에 글을 복사해주세요.'}<span>{draft.originalText.length.toLocaleString()}자</span></div><label className="check"><input type="checkbox" checked={ai} onChange={e=>setAI(e.target.checked)}/> 저장 후 AI로 정리하고 질문 받기</label><p className="small muted">AI 사용 시 이 책의 이전 기록과 답변이 함께 전달됩니다.</p>{error&&<p role="alert" className="error">{error}</p>}<div className="form-actions"><button type="button" onClick={onClose}>나중에 계속 쓰기</button><button className="primary" type="submit">기록 저장</button></div></form></Modal>
}
